name: VPS with Ngrok

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ngrok
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin/

    - name: Start SSH service
      run: |
        sudo apt-get install -y openssh-server
        sudo service ssh start

    - name: Run Ngrok
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok tcp 22 &
        sleep 5
        ngrok_url=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "Ngrok URL: $ngrok_url"
        echo "Ngrok URL: $ngrok_url" > ngrok_url.txt

    - name: Upload Ngrok URL
      uses: actions/upload-artifact@v2
      with:
        name: ngrok-url
        path: ngrok_url.txt
