name: VPS with Ngrok

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ngrok
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip curl jq
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip
        sudo mv ngrok /usr/local/bin/
        ngrok version # Verifikasi versi ngrok

    - name: Start SSH service
      run: |
        sudo apt-get install -y openssh-server
        sudo service ssh start

    - name: Run Ngrok
      run: |
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok tcp 22 > /tmp/ngrok.log &
        sleep 10
        ngrok_url=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        if [ -z "$ngrok_url" ]; then
          echo "Ngrok URL is empty. Check the Ngrok service."
          echo "Ngrok log:"
          cat /tmp/ngrok.log
          exit 1
        fi
        echo "Ngrok URL: $ngrok_url"
        echo "$ngrok_url" > ngrok_url.txt

    - name: Upload Ngrok URL
      uses: actions/upload-artifact@v2
      with:
        name: ngrok-url
        path: ngrok_url.txt
